name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install yarn
      - run: yarn install
      - run: yarn build
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REACT_APP_GITHUB_CLIENT_ID: ${{secrets.REACT_APP_GITHUB_CLIENT_ID}}
          REACT_APP_GITHUB_CLIENT_SECRET: ${{secrets.REACT_APP_GITHUB_CLIENT_SECRET}}
          REACT_APP_GITHUB_AUTH_TOKEN: ${{secrets.REACT_APP_GITHUB_AUTH_TOKEN}}
          REACT_APP_FIREBASE_APIKEY: ${{secrets.REACT_APP_FIREBASE_APIKEY}}
          REACT_APP_FIREBASE_AUTHDOMAIN: ${{secrets.REACT_APP_FIREBASE_AUTHDOMAIN}}
          REACT_APP_FIREBASE_PROJECTID: ${{secrets.REACT_APP_FIREBASE_PROJECTID}}
          REACT_APP_FIREBASE_STORAGEBUCKET: ${{secrets.REACT_APP_FIREBASE_STORAGEBUCKET}}
          REACT_APP_FIREBASE_MESSAGINGSENDERID: ${{secrets.REACT_APP_FIREBASE_MESSAGINGSENDERID}}
          REACT_APP_FIREBASE_APPID: ${{secrets.REACT_APP_FIREBASE_APPID}}
          REACT_APP_FIREBASE_MEASUREMENTID: ${{secrets.REACT_APP_FIREBASE_MEASUREMENTID}}

